version: '3.8'

networks:
  ops1:
    external: false
  accessx_api_net:
    external: true

volumes:
  db_data:
  redis_data:
  ruby_bundle:

services:
  web:
    image: goatatwork/rails:6.1.3-postgresql
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
    volumes:
      - ruby_bundle:/usr/local/bundle
      - ./:/app
      - /Users/tool/.ssh:/root/.ssh
    working_dir: /app
    networks:
      - ops1
      - accessx_api_net
    ports:
      - "3000:3000"
  sidekiq:
    image: goatatwork/rails:6.1.3-postgresql
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_URL_SIDEKIQ=redis://redis:6379/0
    volumes:
      - ruby_bundle:/usr/local/bundle
      - ./:/app
      - /Users/tool/.ssh:/root/.ssh
    working_dir: /app
    networks:
      - ops1
    command: bundle exec sidekiq
  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - ops1
  redis:
    image: redis:6.2.1-alpine
    volumes:
      - redis_data:/data
    labels:
      - traefik.enable=false
    networks:
      - ops1
